let tasks = [
  // COURSE 1 - doing fairly well / near or above goal
  {
    id: "task-1",
    taskId: 1,
    courseId: 1,
    title: "Capstone proposal",
    type: "PROJECT",
    dueDate: "2026-01-20T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 82,
  },
  {
    id: "task-2",
    taskId: 2,
    courseId: 1,
    title: "Research summary",
    type: "ASSIGNMENT",
    dueDate: "2026-02-01T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 78,
  },
  {
    id: "task-3",
    taskId: 3,
    courseId: 1,
    title: "Sprint demo 1",
    type: "PROJECT",
    dueDate: "2026-02-12T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 80,
  },
  {
    id: "task-4",
    taskId: 4,
    courseId: 1,
    title: "Progress report",
    type: "ASSIGNMENT",
    dueDate: "2026-03-01T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 7,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-5",
    taskId: 5,
    courseId: 1,
    title: "Prototype review",
    type: "PROJECT",
    dueDate: "2026-03-18T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 7,
    manualPriorityOverride: true,
    weight: 20,
    scorePercent: 0,
  },
  {
    id: "task-6",
    taskId: 6,
    courseId: 1,
    title: "Final capstone submission",
    type: "PROJECT",
    dueDate: "2026-04-10T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 30,
    scorePercent: 0,
  },

  // COURSE 2 - failing / none completed
  {
    id: "task-7",
    taskId: 7,
    courseId: 2,
    title: "Lab 1",
    type: "LAB",
    dueDate: "2026-01-18T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 0,
  },
  {
    id: "task-8",
    taskId: 8,
    courseId: 2,
    title: "Lab 2",
    type: "LAB",
    dueDate: "2026-02-02T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 0,
  },
  {
    id: "task-9",
    taskId: 9,
    courseId: 2,
    title: "Quiz 1",
    type: "QUIZ",
    dueDate: "2026-02-10T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 2,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 0,
  },
  {
    id: "task-10",
    taskId: 10,
    courseId: 2,
    title: "Midterm",
    type: "EXAM",
    dueDate: "2026-02-24T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 7,
    manualPriorityOverride: false,
    weight: 25,
    scorePercent: 0,
  },
  {
    id: "task-11",
    taskId: 11,
    courseId: 2,
    title: "Security audit report",
    type: "PROJECT",
    dueDate: "2026-03-10T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-12",
    taskId: 12,
    courseId: 2,
    title: "Final exam",
    type: "EXAM",
    dueDate: "2026-04-14T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 30,
    scorePercent: 0,
  },

  // COURSE 3 - middle range
  {
    id: "task-13",
    taskId: 13,
    courseId: 3,
    title: "Requirements analysis",
    type: "ASSIGNMENT",
    dueDate: "2026-01-22T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 72,
  },
  {
    id: "task-14",
    taskId: 14,
    courseId: 3,
    title: "Sprint backlog setup",
    type: "PROJECT",
    dueDate: "2026-02-03T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 74,
  },
  {
    id: "task-15",
    taskId: 15,
    courseId: 3,
    title: "API integration lab",
    type: "LAB",
    dueDate: "2026-02-17T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 68,
  },
  {
    id: "task-16",
    taskId: 16,
    courseId: 3,
    title: "UI prototype",
    type: "PROJECT",
    dueDate: "2026-03-02T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 6,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-17",
    taskId: 17,
    courseId: 3,
    title: "Sprint review 2",
    type: "PROJECT",
    dueDate: "2026-03-16T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-18",
    taskId: 18,
    courseId: 3,
    title: "Final full stack project",
    type: "PROJECT",
    dueDate: "2026-04-12T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 35,
    scorePercent: 0,
  },

  // COURSE 4 - lower-middle
  {
    id: "task-19",
    taskId: 19,
    courseId: 4,
    title: "Storyboard wireframes",
    type: "ASSIGNMENT",
    dueDate: "2026-01-21T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 70,
  },
  {
    id: "task-20",
    taskId: 20,
    courseId: 4,
    title: "Swift UI practice lab",
    type: "LAB",
    dueDate: "2026-02-05T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 66,
  },
  {
    id: "task-21",
    taskId: 21,
    courseId: 4,
    title: "Navigation flow demo",
    type: "PROJECT",
    dueDate: "2026-02-19T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-22",
    taskId: 22,
    courseId: 4,
    title: "API consumption assignment",
    type: "ASSIGNMENT",
    dueDate: "2026-03-05T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-23",
    taskId: 23,
    courseId: 4,
    title: "Midterm practical",
    type: "TEST",
    dueDate: "2026-03-12T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 7,
    manualPriorityOverride: false,
    weight: 20,
    scorePercent: 0,
  },
  {
    id: "task-24",
    taskId: 24,
    courseId: 4,
    title: "Final mobile app build",
    type: "PROJECT",
    dueDate: "2026-04-08T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 30,
    scorePercent: 0,
  },

  // COURSE 5 - mixed / moderate progress
  {
    id: "task-25",
    taskId: 25,
    courseId: 5,
    title: "ER diagram",
    type: "ASSIGNMENT",
    dueDate: "2026-01-19T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 8,
    scorePercent: 76,
  },
  {
    id: "task-26",
    taskId: 26,
    courseId: 5,
    title: "SQL queries lab",
    type: "LAB",
    dueDate: "2026-02-01T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 12,
    scorePercent: 81,
  },
  {
    id: "task-27",
    taskId: 27,
    courseId: 5,
    title: "Normalization exercise",
    type: "ASSIGNMENT",
    dueDate: "2026-02-13T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 74,
  },
  {
    id: "task-28",
    taskId: 28,
    courseId: 5,
    title: "Midterm test",
    type: "TEST",
    dueDate: "2026-02-27T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 7,
    manualPriorityOverride: false,
    weight: 20,
    scorePercent: 0,
  },
  {
    id: "task-29",
    taskId: 29,
    courseId: 5,
    title: "Stored procedures lab",
    type: "LAB",
    dueDate: "2026-03-11T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 0,
  },
  {
    id: "task-30",
    taskId: 30,
    courseId: 5,
    title: "Final database project",
    type: "PROJECT",
    dueDate: "2026-04-11T17:00:00",
    isCompleted: false,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 35,
    scorePercent: 0,
  },

  // COURSE 6 - all completed / meeting goal
  {
    id: "task-31",
    taskId: 31,
    courseId: 6,
    title: "HTML/CSS review",
    type: "LAB",
    dueDate: "2026-01-17T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 92,
  },
  {
    id: "task-32",
    taskId: 32,
    courseId: 6,
    title: "React components assignment",
    type: "ASSIGNMENT",
    dueDate: "2026-01-30T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 4,
    manualPriorityOverride: false,
    weight: 15,
    scorePercent: 88,
  },
  {
    id: "task-33",
    taskId: 33,
    courseId: 6,
    title: "State management quiz",
    type: "QUIZ",
    dueDate: "2026-02-11T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 2,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 90,
  },
  {
    id: "task-34",
    taskId: 34,
    courseId: 6,
    title: "Routing lab",
    type: "LAB",
    dueDate: "2026-02-20T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 3,
    manualPriorityOverride: false,
    weight: 10,
    scorePercent: 94,
  },
  {
    id: "task-35",
    taskId: 35,
    courseId: 6,
    title: "Midterm project",
    type: "PROJECT",
    dueDate: "2026-03-06T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 6,
    manualPriorityOverride: false,
    weight: 20,
    scorePercent: 87,
  },
  {
    id: "task-36",
    taskId: 36,
    courseId: 6,
    title: "Final web app",
    type: "PROJECT",
    dueDate: "2026-04-09T17:00:00",
    isCompleted: true,
    isBonus: false,
    isPriority: true,
    priorityThresholdDays: 10,
    manualPriorityOverride: false,
    weight: 35,
    scorePercent: 91,
  },

  // COURSE 7 - intentionally no tasks
];

function nextId() {
  return tasks.length ? Math.max(...tasks.map((t) => Number(t.taskId))) + 1 : 1;
}

export async function getTasks() {
  return structuredClone(tasks);
}

export async function createTask(payload) {
  const newTask = {
    id: `task-${nextId()}`,
    taskId: nextId(),
    title: "",
    type: "ASSIGNMENT",
    dueDate: null,
    isCompleted: false,
    isBonus: false,
    isPriority: false,
    priorityThresholdDays: 5,
    manualPriorityOverride: false,
    weight: 0,
    scorePercent: 0,
    courseId: null,
    ...payload,
  };
  tasks = [...tasks, newTask];
  return structuredClone(newTask);
}

export async function updateTask(id, payload) {
  const numericId = Number(id);
  const existing = tasks.find((t) => Number(t.taskId) === numericId);
  const updated = {
    ...existing,
    ...payload,
    taskId: numericId,
    id: existing?.id ?? `task-${numericId}`,
  };

  tasks = tasks.map((t) =>
    Number(t.taskId) === numericId ? updated : t
  );

  return structuredClone(updated);
}

export async function deleteTask(id) {
  const numericId = Number(id);
  tasks = tasks.filter((t) => Number(t.taskId) !== numericId);
  return true;
}